[tools]
actionlint = "1.7.12"
bun = "1.3.14"
cocogitto = "7.0.0"
gitleaks = "8.30.0"
"github:lycheeverse/lychee" = "lychee-v0.23.0"
pkl = "0.31.1"
zizmor = "1.25.2"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]

[deps.bun]
auto = true
