// This file is generated by `bun run generated-dependencies:sync`.
// Edit config/generated-dependencies/baseline.pkl instead.
// Domain language: config/generated-dependencies/UBIQUITOUS_LANGUAGE.md.
export type GeneratedPackageName = string;
export type GeneratedPackageVersion = string;
export type DependencyTarget =
  | "root.dependencies"
  | "root.devDependencies"
  | "frontend.dependencies"
  | "frontend.devDependencies";

export type GeneratedDependencyConditions = {
  readonly backend?: boolean;
  readonly frontend?: "tanstack";
  readonly ai?: boolean;
  readonly effect?: boolean;
};

export type GeneratedDependencyPackage = {
  readonly version: GeneratedPackageVersion;
  readonly sharedWithParent: boolean;
  readonly compatibilityGroup?: string;
};

export type GeneratedDependencyEmission = {
  readonly packageName: GeneratedPackageName;
  readonly version: GeneratedPackageVersion;
  readonly conditions?: GeneratedDependencyConditions;
};

export type CompatibilityGroupPolicy = "same-major" | "review-together";

export type GeneratedDependencyCompatibilityGroup = {
  readonly policy: CompatibilityGroupPolicy;
  readonly packages: readonly GeneratedPackageName[];
};

export const GENERATED_DEPENDENCY_PACKAGES = {
  "@commitlint/cli": {
    sharedWithParent: true,
    version: "21.0.1",
  },
  "@commitlint/config-conventional": {
    sharedWithParent: true,
    version: "21.0.1",
  },
  "@effect/language-service": {
    sharedWithParent: false,
    version: "0.85.1",
  },
  "@effect/platform": {
    sharedWithParent: false,
    version: "0.96.1",
  },
  "@effect/platform-bun": {
    sharedWithParent: false,
    version: "0.89.0",
  },
  "@playwright/test": {
    sharedWithParent: false,
    version: "1.59.1",
  },
  "@tanstack/react-router": {
    compatibilityGroup: "tanstack-router",
    sharedWithParent: false,
    version: "1.169.2",
  },
  "@tanstack/router-plugin": {
    compatibilityGroup: "tanstack-router",
    sharedWithParent: false,
    version: "1.167.35",
  },
  "@testing-library/dom": {
    sharedWithParent: false,
    version: "10.4.1",
  },
  "@testing-library/jest-dom": {
    sharedWithParent: false,
    version: "6.9.1",
  },
  "@testing-library/react": {
    sharedWithParent: false,
    version: "16.3.2",
  },
  "@types/bun": {
    sharedWithParent: true,
    version: "1.3.14",
  },
  "@types/node": {
    sharedWithParent: false,
    version: "25.6.0",
  },
  "@types/react": {
    compatibilityGroup: "react-types",
    sharedWithParent: false,
    version: "19.2.14",
  },
  "@types/react-dom": {
    compatibilityGroup: "react-types",
    sharedWithParent: false,
    version: "19.2.3",
  },
  "@vitejs/plugin-react": {
    sharedWithParent: false,
    version: "6.0.1",
  },
  "dependency-cruiser": {
    sharedWithParent: true,
    version: "17.4.0",
  },
  effect: {
    sharedWithParent: false,
    version: "3.21.2",
  },
  jscpd: {
    sharedWithParent: true,
    version: "4.2.2",
  },
  jsdom: {
    sharedWithParent: false,
    version: "29.1.1",
  },
  knip: {
    sharedWithParent: true,
    version: "6.14.1",
  },
  lefthook: {
    sharedWithParent: true,
    version: "2.1.6",
  },
  oxfmt: {
    sharedWithParent: true,
    version: "0.50.0",
  },
  oxlint: {
    sharedWithParent: true,
    version: "1.65.0",
  },
  "oxlint-plugin-complexity": {
    sharedWithParent: true,
    version: "2.1.2",
  },
  "oxlint-tsgolint": {
    sharedWithParent: true,
    version: "0.22.1",
  },
  react: {
    compatibilityGroup: "react-types",
    sharedWithParent: false,
    version: "19.2.6",
  },
  "react-dom": {
    compatibilityGroup: "react-types",
    sharedWithParent: false,
    version: "19.2.6",
  },
  stylelint: {
    sharedWithParent: false,
    version: "17.11.0",
  },
  typescript: {
    sharedWithParent: true,
    version: "6.0.3",
  },
  vite: {
    sharedWithParent: false,
    version: "8.0.11",
  },
  vitest: {
    sharedWithParent: false,
    version: "4.1.5",
  },
} as const satisfies Readonly<Record<GeneratedPackageName, GeneratedDependencyPackage>>;

export const GENERATED_DEPENDENCY_EMISSIONS_BY_TARGET = {
  "frontend.dependencies": [
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@tanstack/react-router",
      version: "1.169.2",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "react",
      version: "19.2.6",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "react-dom",
      version: "19.2.6",
    },
  ],
  "frontend.devDependencies": [
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@playwright/test",
      version: "1.59.1",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@tanstack/router-plugin",
      version: "1.167.35",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@testing-library/dom",
      version: "10.4.1",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@testing-library/jest-dom",
      version: "6.9.1",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@testing-library/react",
      version: "16.3.2",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@types/node",
      version: "25.6.0",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@types/react",
      version: "19.2.14",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@types/react-dom",
      version: "19.2.3",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "@vitejs/plugin-react",
      version: "6.0.1",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "jsdom",
      version: "29.1.1",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "oxfmt",
      version: "0.50.0",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "oxlint",
      version: "1.65.0",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "oxlint-tsgolint",
      version: "0.22.1",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "stylelint",
      version: "17.11.0",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "typescript",
      version: "6.0.3",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "vite",
      version: "8.0.11",
    },
    {
      conditions: {
        frontend: "tanstack",
      },
      packageName: "vitest",
      version: "4.1.5",
    },
  ],
  "root.dependencies": [
    {
      conditions: {
        effect: true,
      },
      packageName: "@effect/platform",
      version: "0.96.1",
    },
    {
      conditions: {
        effect: true,
      },
      packageName: "@effect/platform-bun",
      version: "0.89.0",
    },
    {
      conditions: {
        effect: true,
      },
      packageName: "effect",
      version: "3.21.2",
    },
  ],
  "root.devDependencies": [
    {
      packageName: "@commitlint/cli",
      version: "21.0.1",
    },
    {
      packageName: "@commitlint/config-conventional",
      version: "21.0.1",
    },
    {
      conditions: {
        effect: true,
      },
      packageName: "@effect/language-service",
      version: "0.85.1",
    },
    {
      packageName: "@types/bun",
      version: "1.3.14",
    },
    {
      packageName: "dependency-cruiser",
      version: "17.4.0",
    },
    {
      packageName: "jscpd",
      version: "4.2.2",
    },
    {
      packageName: "knip",
      version: "6.14.1",
    },
    {
      packageName: "lefthook",
      version: "2.1.6",
    },
    {
      packageName: "oxfmt",
      version: "0.50.0",
    },
    {
      packageName: "oxlint",
      version: "1.65.0",
    },
    {
      packageName: "oxlint-plugin-complexity",
      version: "2.1.2",
    },
    {
      packageName: "oxlint-tsgolint",
      version: "0.22.1",
    },
    {
      packageName: "typescript",
      version: "6.0.3",
    },
  ],
} as const satisfies Readonly<Record<DependencyTarget, readonly GeneratedDependencyEmission[]>>;

export const GENERATED_DEPENDENCY_COMPATIBILITY_GROUPS = {
  "react-types": {
    packages: ["@types/react", "@types/react-dom", "react", "react-dom"],
    policy: "same-major",
  },
  "tanstack-router": {
    packages: ["@tanstack/react-router", "@tanstack/router-plugin"],
    policy: "review-together",
  },
} as const satisfies Readonly<Record<string, GeneratedDependencyCompatibilityGroup>>;
